version: 0.2
phases:
  install:
    runtime-version:
      python: 3.9
    commands:
      - echo "Insatlling dependencies"
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo  "Zipping deployement"
      - cd lib
      - zip -r9 ../deployment_package.zip
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading function"
      - aws lambda update-function-code --function-name github-to-lambda-demo cicd-lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
      
      
